import express from "express";import multer from "multer";import QRCode from "qrcode";import fs from "fs";import path from "path";import crypto from "crypto";import{fileURLToPath}from"url";
const __dirname=path.dirname(fileURLToPath(import.meta.url)),app=express(),PORT=process.env.PORT||3000,ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"DEGISTIR",SITE_URL=process.env.SITE_URL||`http://localhost:${PORT}`,uploadDir=process.env.UPLOAD_DIR||path.join(__dirname,"uploads");fs.mkdirSync(uploadDir,{recursive:true});app.use(express.json());app.use(express.static(path.join(__dirname,"public")));
const allowed=new Set(["image/jpeg","image/png","image/webp","image/heic","image/heif"]);const storage=multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>cb(null,`${Date.now()}-${crypto.randomBytes(8).toString("hex")}${path.extname(file.originalname).toLowerCase()}`)});const upload=multer({storage,limits:{fileSize:15*1024*1024,files:20},fileFilter:(req,file,cb)=>cb(null,allowed.has(file.mimetype))});const sessions=new Set();
function mimeFor(n){return({".jpg":"image/jpeg",".jpeg":"image/jpeg",".png":"image/png",".webp":"image/webp",".heic":"image/heic",".heif":"image/heif"})[path.extname(n).toLowerCase()]||"application/octet-stream"}function auth(req,res,next){const t=req.headers.authorization?.replace("Bearer ","");if(!t||!sessions.has(t))return res.status(401).json({error:"Yetkisiz"});next()}
app.get("/",(req,res)=>res.redirect("/upload"));app.get("/upload",(req,res)=>res.sendFile(path.join(__dirname,"public","upload.html")));app.get("/admin",(req,res)=>res.sendFile(path.join(__dirname,"public","admin.html")));app.get("/health",(req,res)=>res.send("ok"));
app.post("/api/upload",upload.array("photos",20),(req,res)=>res.json({ok:true,count:(req.files||[]).length}));
app.post("/api/login",(req,res)=>{if(req.body?.password!==ADMIN_PASSWORD)return res.status(401).json({error:"Şifre hatalı"});const t=crypto.randomBytes(32).toString("hex");sessions.add(t);res.json({token:t})});
app.get("/api/photos",auth,(req,res)=>{const a=fs.readdirSync(uploadDir).filter(f=>allowed.has(mimeFor(f))).map(name=>{const s=fs.statSync(path.join(uploadDir,name));return{id:name,uploadedAt:s.mtime.toISOString()}}).sort((a,b)=>b.uploadedAt.localeCompare(a.uploadedAt));res.json(a)});
app.get("/api/photo/:name",auth,(req,res)=>{const n=path.basename(req.params.name),p=path.join(uploadDir,n);if(!fs.existsSync(p))return res.sendStatus(404);res.type(mimeFor(n)).sendFile(p)});
app.get("/api/photo/:name/download",auth,(req,res)=>{const n=path.basename(req.params.name),p=path.join(uploadDir,n);if(!fs.existsSync(p))return res.sendStatus(404);res.download(p,n)});
app.delete("/api/photo/:name",auth,(req,res)=>{const p=path.join(uploadDir,path.basename(req.params.name));if(fs.existsSync(p))fs.unlinkSync(p);res.json({ok:true})});
app.get("/api/qr",async(req,res)=>res.type("png").send(await QRCode.toBuffer(`${SITE_URL}/upload`,{width:900,margin:2})));app.listen(PORT,"0.0.0.0",()=>console.log(`Site: ${SITE_URL}`));